version: "3.9"
services:
  web:
    container_name: ${PROJECT}
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ${PROJECTPATH}\${PROJECT}:/root/${PROJECT}
    working_dir: /root/${PROJECT}
    command:
      - /bin/bash
      - -c
      - |
       npm install
       tail -f /dev/null
      #  npm start



